name: Spread Tests

on:
  workflow_call:
    inputs:
      tests:
        description: Spread tests to run
        type: string
        required: true

jobs:
  spread-tests:
    name: ${{ matrix.test }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(inputs.tests) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.2

      - name: Run integration tests
        run: nix develop -c spread -v "${{ matrix.test }}"
